name: Frontend CI/CD via SSM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build step
        run: |
          echo "Building frontend..."
          echo "Build completed!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::356630932809:role/DevOps-Infra
          aws-region: us-east-1

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
           --instance-ids i-0f799f43c77cda5f5 \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Uptime Kuma Frontend" \
            --parameters commands='[
              "mkdir -p /var/www/frontend",
              "cd /var/www/frontend",
              "git clone https://github.com/RwaydaSalah/uptime-kuma-frontend.git .",
              "cd docker",
              "docker compose -f docker-compose-dev.yml up -d",
              "docker image prune -f"
            ]' \
            --output text
